In [29]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier


In [31]:
mydata=pd.read_csv('datatraining.txt')

In [35]:
mydata.head()

date  Temperature  Humidity  Light     CO2  HumidityRatio  \
1  2015-02-04 17:51:00        23.18   27.2720  426.0  721.25       0.004793   
2  2015-02-04 17:51:59        23.15   27.2675  429.5  714.00       0.004783   
3  2015-02-04 17:53:00        23.15   27.2450  426.0  713.50       0.004779   
4  2015-02-04 17:54:00        23.15   27.2000  426.0  708.25       0.004772   
5  2015-02-04 17:55:00        23.10   27.2000  426.0  704.50       0.004757   

   Occupancy  
1          1  
2          1  
3          1  
4          1  
5          1

In [36]:
mydata.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8143 entries, 1 to 8143
Data columns (total 7 columns):
date             8143 non-null object
Temperature      8143 non-null float64
Humidity         8143 non-null float64
Light            8143 non-null float64
CO2              8143 non-null float64
HumidityRatio    8143 non-null float64
Occupancy        8143 non-null int64
dtypes: float64(5), int64(1), object(1)
memory usage: 477.1+ KB


In [59]:
test1=pd.read_csv('datatest.txt')

In [62]:
X_train=mydata.iloc[:,1:6].values
y_train=mydata.iloc[:,6].values
X_test=test1.iloc[:,1:6].values
y_test=test1.iloc[:,6].values

In [51]:
clf=DecisionTreeClassifier()

In [52]:
mydata.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8143 entries, 1 to 8143
Data columns (total 7 columns):
date             8143 non-null object
Temperature      8143 non-null float64
Humidity         8143 non-null float64
Light            8143 non-null float64
CO2              8143 non-null float64
HumidityRatio    8143 non-null float64
Occupancy        8143 non-null int64
dtypes: float64(5), int64(1), object(1)
memory usage: 477.1+ KB


In [54]:
clf.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [55]:
print("Training Confusion Matrix\n", confusion_matrix(y_train,clf.predict(X_train)))

Training Confusion Matrix
 [[6414    0]
 [   0 1729]]


In [63]:
print("Testing Confusion Matrix\n", confusion_matrix(y_test,clf.predict(X_test)))

Testing Confusion Matrix
 [[1666   27]
 [ 244  728]]


In [66]:
print("Training Accuracy\n", accuracy_score(y_train,clf.predict(X_train)))
print("Testing Accuracy\n", accuracy_score(y_test,clf.predict(X_test)))

Training Accuracy
 1.0
Testing Accuracy
 0.898311444652908


In [67]:
from sklearn.metrics import classification_report
print("Training\n", classification_report(y_train,clf.predict(X_train)))
print("Testing \n", classification_report(y_test,clf.predict(X_test)))

Training
              precision    recall  f1-score   support

          0       1.00      1.00      1.00      6414
          1       1.00      1.00      1.00      1729

avg / total       1.00      1.00      1.00      8143

Testing 
              precision    recall  f1-score   support

          0       0.87      0.98      0.92      1693
          1       0.96      0.75      0.84       972

avg / total       0.91      0.90      0.89      2665



In [68]:
clf1=DecisionTreeClassifier(criterion="entropy")

In [69]:
clf1.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [70]:
print("Training Confusion Matrix\n", confusion_matrix(y_train,clf1.predict(X_train)))

Training Confusion Matrix
 [[6414    0]
 [   0 1729]]


In [72]:
print("Testing Confusion Matrix\n", confusion_matrix(y_test,clf1.predict(X_test)))

Testing Confusion Matrix
 [[1643   50]
 [ 239  733]]


In [73]:
print("Training Accuracy\n", accuracy_score(y_train,clf1.predict(X_train)))
print("Testing Accuracy\n", accuracy_score(y_test,clf1.predict(X_test)))

Training Accuracy
 1.0
Testing Accuracy
 0.8915572232645403


In [74]:
print("Training\n", classification_report(y_train,clf1.predict(X_train)))
print("Testing \n", classification_report(y_test,clf1.predict(X_test)))

Training
              precision    recall  f1-score   support

          0       1.00      1.00      1.00      6414
          1       1.00      1.00      1.00      1729

avg / total       1.00      1.00      1.00      8143

Testing 
              precision    recall  f1-score   support

          0       0.87      0.97      0.92      1693
          1       0.94      0.75      0.84       972

avg / total       0.90      0.89      0.89      2665

