In [81]:
import numpy as np  
import pandas as pd  
from sklearn.model_selection import train_test_split


In [82]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"  
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']  
data = pd.read_csv(url, names=names)  

In [83]:
data.head()

sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [84]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
sepal-length    150 non-null float64
sepal-width     150 non-null float64
petal-length    150 non-null float64
petal-width     150 non-null float64
Class           150 non-null object
dtypes: float64(4), object(1)
memory usage: 5.3+ KB


In [85]:
data.isnull().sum()

sepal-length    0
sepal-width     0
petal-length    0
petal-width     0
Class           0
dtype: int64

In [86]:
X = data.iloc[:, 0:4].values  
y = data.iloc[:, 4].values  

In [87]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=40)  

In [88]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()  
X_train = sc.fit_transform(X_train)  
X_test = sc.transform(X_test)  


In [89]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(max_depth=2, random_state=40)

clf.fit(X_train, y_train)  
y_pred = clf.predict(X_test) 

In [90]:
from sklearn.metrics import confusion_matrix  
from sklearn.metrics import accuracy_score

print ('Without ')
cm = confusion_matrix(y_test, y_pred)  
print(cm)  
print('Accuracy : ' + str(accuracy_score(y_test, y_pred)))  


Without 
[[16  0  0]
 [ 0 14  0]
 [ 0  3 12]]
Accuracy : 0.933333333333


In [91]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

lda = LDA(n_components=2)  
X_train = lda.fit_transform(X_train, y_train)  
X_test = lda.transform(X_test)  


In [100]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(max_depth=2, random_state=20)

clf.fit(X_train, y_train)  
y_pred = clf.predict(X_test) 

In [99]:
from sklearn.metrics import confusion_matrix  
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)  
print(cm)  
print('Accuracy : ' + str(accuracy_score(y_test, y_pred)))  

[[16  0  0]
 [ 0 14  0]
 [ 0  4 11]]
Accuracy : 0.911111111111
